#!/bin/sh
#
# Starts idleinject daemon
#

DAEMON="idleinject"

umask 077

start() {
	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -S -q -m -p /var/run/idleinject.pid -b --exec @BINDIR@/idleinject
	echo "OK"
}
stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -m -p /var/run/idleinject.pid -b --exec @BINDIR@/idleinject
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
