#!/bin/sh
#
# Starts cukinia system test
#

DAEMON="cukinia"

umask 077

start() {
	printf 'Starting %s: ' "$DAEMON"
	start-stop-daemon -S -m -p /var/run/cukinia.pid -b --exec /usr/sbin/cukinia -- -f junitxml -o /results.xml /etc/cukinia.conf
	echo "OK"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -m -p /var/run/cukinia.pid -b --exec /usr/sbin/cukinia
	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
