cukinia_cmd ifup wlan0
gateway=$(ip route show default dev wlan0 | cut -d' ' -f3)
ssid=$(iw dev wlan0 link|grep SSID | cut -d' ' -f 2)
cukinia_test "$ssid" = "engineering_test"
cukinia_cmd "ping -c5 $gateway"
