BT_DEVICE="/dev/ttymxc2"

cukinia_conf_include /etc/cukinia.d/common.conf

cukinia_conf_include /etc/cukinia.d/tssilomon.conf

cukinia_conf_include /etc/cukinia.d/wifi.conf

cukinia_conf_include /etc/cukinia.d/bt_wilc3000.conf
